/*
Purpose:
  Create the minimal Azure SQL source schema in sub2 for the synthetic Enercare
  transactional dataset generated by demo/fabric/nb_01_setup_demo_environment.py.

Scope:
  This script intentionally models the seven source tables consumed by
  demo/fabric/nb_02_pbi_star_schema.py:
    - products
    - customers
    - service_accounts
    - equipment_registry
    - contracts
    - service_requests
    - billing_transactions

Notes:
  - IDs are loaded from the synthetic dataset and are not defined as IDENTITY.
  - The Fabric star schema remains downstream in sub1; this script defines only
    the sub2 source layer.
*/

SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.billing_transactions', N'U') IS NOT NULL DROP TABLE dbo.billing_transactions;
IF OBJECT_ID(N'dbo.service_requests', N'U') IS NOT NULL DROP TABLE dbo.service_requests;
IF OBJECT_ID(N'dbo.contracts', N'U') IS NOT NULL DROP TABLE dbo.contracts;
IF OBJECT_ID(N'dbo.equipment_registry', N'U') IS NOT NULL DROP TABLE dbo.equipment_registry;
IF OBJECT_ID(N'dbo.service_accounts', N'U') IS NOT NULL DROP TABLE dbo.service_accounts;
IF OBJECT_ID(N'dbo.customers', N'U') IS NOT NULL DROP TABLE dbo.customers;
IF OBJECT_ID(N'dbo.products', N'U') IS NOT NULL DROP TABLE dbo.products;
GO

CREATE TABLE dbo.products (
    product_id         INT            NOT NULL,
    product_code       VARCHAR(32)    NOT NULL,
    product_name       NVARCHAR(200)  NOT NULL,
    product_category   VARCHAR(32)    NOT NULL,
    billing_frequency  VARCHAR(16)    NOT NULL,
    base_price         DECIMAL(10, 2) NOT NULL,
    is_active          BIT            NOT NULL,
    effective_date     DATE           NOT NULL,
    CONSTRAINT PK_products PRIMARY KEY CLUSTERED (product_id),
    CONSTRAINT UQ_products_product_code UNIQUE (product_code)
);
GO

CREATE TABLE dbo.customers (
    customer_id       INT            NOT NULL,
    account_number    VARCHAR(20)    NOT NULL,
    first_name        NVARCHAR(100)  NULL,
    last_name         NVARCHAR(100)  NULL,
    email             VARCHAR(255)   NULL,
    phone             VARCHAR(25)    NULL,
    customer_type     VARCHAR(32)    NOT NULL,
    status            VARCHAR(32)    NOT NULL,
    city              NVARCHAR(100)  NULL,
    province          CHAR(2)        NOT NULL,
    postal_code       VARCHAR(10)    NULL,
    created_date      DATE           NOT NULL,
    CONSTRAINT PK_customers PRIMARY KEY CLUSTERED (customer_id),
    CONSTRAINT UQ_customers_account_number UNIQUE (account_number)
);
GO

CREATE TABLE dbo.service_accounts (
    service_account_id  INT            NOT NULL,
    customer_id         INT            NOT NULL,
    account_number      VARCHAR(24)    NOT NULL,
    utility_type        VARCHAR(32)    NOT NULL,
    rate_class          VARCHAR(64)    NULL,
    distributor         VARCHAR(64)    NULL,
    status              VARCHAR(32)    NOT NULL,
    service_address     NVARCHAR(200)  NULL,
    city                NVARCHAR(100)  NULL,
    postal_code         VARCHAR(10)    NULL,
    opened_date         DATE           NOT NULL,
    CONSTRAINT PK_service_accounts PRIMARY KEY CLUSTERED (service_account_id),
    CONSTRAINT UQ_service_accounts_account_number UNIQUE (account_number),
    CONSTRAINT FK_service_accounts_customers FOREIGN KEY (customer_id)
        REFERENCES dbo.customers (customer_id)
);
GO

CREATE TABLE dbo.equipment_registry (
    equipment_id        INT            NOT NULL,
    service_account_id  INT            NOT NULL,
    equipment_type      VARCHAR(50)    NOT NULL,
    make                NVARCHAR(100)  NULL,
    model               NVARCHAR(150)  NULL,
    serial_number       VARCHAR(50)    NULL,
    ownership_type      VARCHAR(32)    NOT NULL,
    fuel_type           VARCHAR(32)    NULL,
    install_date        DATE           NULL,
    warranty_expiry     DATE           NULL,
    status              VARCHAR(32)    NOT NULL,
    CONSTRAINT PK_equipment_registry PRIMARY KEY CLUSTERED (equipment_id),
    CONSTRAINT UQ_equipment_registry_serial_number UNIQUE (serial_number),
    CONSTRAINT FK_equipment_registry_service_accounts FOREIGN KEY (service_account_id)
        REFERENCES dbo.service_accounts (service_account_id)
);
GO

CREATE TABLE dbo.contracts (
    contract_id           INT            NOT NULL,
    service_account_id    INT            NOT NULL,
    product_id            INT            NOT NULL,
    contract_status       VARCHAR(32)    NOT NULL,
    start_date            DATE           NOT NULL,
    end_date              DATE           NULL,
    monthly_amount        DECIMAL(10, 2) NOT NULL,
    auto_renew            BIT            NOT NULL,
    cancellation_date     DATE           NULL,
    cancellation_reason   NVARCHAR(200)  NULL,
    CONSTRAINT PK_contracts PRIMARY KEY CLUSTERED (contract_id),
    CONSTRAINT FK_contracts_service_accounts FOREIGN KEY (service_account_id)
        REFERENCES dbo.service_accounts (service_account_id),
    CONSTRAINT FK_contracts_products FOREIGN KEY (product_id)
        REFERENCES dbo.products (product_id)
);
GO

CREATE TABLE dbo.service_requests (
    request_id           INT            NOT NULL,
    service_account_id   INT            NOT NULL,
    equipment_id         INT            NULL,
    request_type         VARCHAR(50)    NOT NULL,
    priority             VARCHAR(20)    NOT NULL,
    status               VARCHAR(32)    NOT NULL,
    description          NVARCHAR(500)  NULL,
    created_date         DATE           NOT NULL,
    scheduled_date       DATE           NULL,
    completed_date       DATE           NULL,
    technician_id        INT            NULL,
    no_show_reason_code  VARCHAR(64)    NULL,
    resolution_notes     NVARCHAR(500)  NULL,
    CONSTRAINT PK_service_requests PRIMARY KEY CLUSTERED (request_id),
    CONSTRAINT FK_service_requests_service_accounts FOREIGN KEY (service_account_id)
        REFERENCES dbo.service_accounts (service_account_id),
    CONSTRAINT FK_service_requests_equipment FOREIGN KEY (equipment_id)
        REFERENCES dbo.equipment_registry (equipment_id)
);
GO

CREATE TABLE dbo.billing_transactions (
    transaction_id       INT            NOT NULL,
    contract_id          INT            NOT NULL,
    service_account_id   INT            NOT NULL,
    transaction_type     VARCHAR(32)    NOT NULL,
    transaction_date     DATE           NOT NULL,
    due_date             DATE           NULL,
    amount               DECIMAL(10, 2) NOT NULL,
    tax_amount           DECIMAL(10, 2) NOT NULL,
    payment_method       VARCHAR(32)    NULL,
    status               VARCHAR(32)    NOT NULL,
    invoice_number       VARCHAR(50)    NULL,
    CONSTRAINT PK_billing_transactions PRIMARY KEY CLUSTERED (transaction_id),
    CONSTRAINT FK_billing_transactions_contracts FOREIGN KEY (contract_id)
        REFERENCES dbo.contracts (contract_id),
    CONSTRAINT FK_billing_transactions_service_accounts FOREIGN KEY (service_account_id)
        REFERENCES dbo.service_accounts (service_account_id)
);
GO

CREATE INDEX IX_service_accounts_customer_id
    ON dbo.service_accounts (customer_id);
GO

CREATE INDEX IX_equipment_registry_service_account_id
    ON dbo.equipment_registry (service_account_id);
GO

CREATE INDEX IX_contracts_service_account_id
    ON dbo.contracts (service_account_id);
GO

CREATE INDEX IX_contracts_product_id
    ON dbo.contracts (product_id);
GO

CREATE INDEX IX_service_requests_service_account_id
    ON dbo.service_requests (service_account_id);
GO

CREATE INDEX IX_service_requests_equipment_id
    ON dbo.service_requests (equipment_id);
GO

CREATE INDEX IX_billing_transactions_contract_id
    ON dbo.billing_transactions (contract_id);
GO

CREATE INDEX IX_billing_transactions_service_account_id
    ON dbo.billing_transactions (service_account_id);
GO

CREATE INDEX IX_billing_transactions_transaction_date
    ON dbo.billing_transactions (transaction_date);
GO